# Generated by Django 4.2.6 on 2023-10-22 18:33

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditParameters",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("month", models.CharField(max_length=10)),
                ("occupation", models.CharField(max_length=100)),
                ("type_of_loans", models.CharField(max_length=100)),
                ("delay_from_due_date", models.CharField(max_length=10)),
                ("credit_mix", models.CharField(max_length=100)),
                ("payment_of_minimum_amount", models.CharField(max_length=10)),
                (
                    "payment_behaviour",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("poor", "Poor Credit"),
                            ("standard", "Standard Credit"),
                            ("good", "Good Credit"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="qualification type",
                    ),
                ),
                ("changed_credit_limit", models.CharField(max_length=10)),
                ("credit_history_age", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("annual_income", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "monthly_in_hand_salary",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("number_of_bank_accounts", models.IntegerField()),
                ("number_of_credit_cards", models.IntegerField()),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("number_of_loans", models.IntegerField()),
                ("number_of_delayed_payment", models.IntegerField()),
                ("num_credit_inquiries", models.IntegerField()),
                (
                    "outstanding_debt",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "credit_utilization_ratio",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "total_emi_per_month",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "amount_invested_monthly",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "monthly_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "credit_score",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("poor", "Poor Credit"),
                            ("standard", "Standard Credit"),
                            ("good", "Good Credit"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="qualification type",
                    ),
                ),
            ],
        ),
    ]
