# Generated by Django 4.2.6 on 2023-10-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("month", models.CharField(max_length=10)),
                ("occupation", models.CharField(max_length=100)),
                ("type_of_loan", models.CharField(max_length=100)),
                ("delay_from_due_date", models.CharField(max_length=10)),
                ("credit_mix", models.CharField(max_length=100)),
                ("payment_of_min_amount", models.CharField(max_length=10)),
                ("payment_behaviour", models.CharField(max_length=100)),
                ("changed_credit_limit", models.CharField(max_length=10)),
                ("credit_history_age", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("annual_income", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "monthly_inhand_salary",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("num_bank_accounts", models.IntegerField()),
                ("num_credit_card", models.IntegerField()),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("num_of_loan", models.IntegerField()),
                ("num_of_delayed_payment", models.IntegerField()),
                ("num_credit_inquiries", models.IntegerField()),
                (
                    "outstanding_debt",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "credit_utilization_ratio",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "total_emi_per_month",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "amount_invested_monthly",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "monthly_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
